### ISSUE TITLE
Audio processing error: Stream.read() got an unexpected keyword argument 'exception_on_overflow'

### ISSUE THREAD

**Issue by EmiliaBlasten** [HopefulOpal/Aria#1]
After starting `python main.py` and starting any kind of live voice exercise, I get spammed by
```
Audio processing error: Stream.read() got an unexpected keyword argument 'exception_on_overflow'
```
and the program doesn't do anything useful.

Apparently the keyword `exception_on_overflow` doesn't exist for pyaudio prior to version 0.2.11 (I have 0.2.8). On my system, I solved the issue by changing the following line in `voice_core.py`
```
self.stream.read(self.analyzer.CHUNK, exception_on_overflow=False)
```
into this:
```
self.stream.read(self.analyzer.CHUNK)
```

I don't know enough python to code a proper fix (perhaps some try - except magic to see if the keyword argument exists, then decide to call it or not?).

**Comment by HopefulOpal** [comment]
Good catch! Going to push an updated clean fallback for older PyAudio versions:
```
  try:
      data = self.stream.read(self.analyzer.CHUNK, exception_on_overflow=False)
  except TypeError:
      # Fallback for PyAudio < 0.2.11
      data = self.stream.read(self.analyzer.CHUNK)

```
  Works with both your 0.2.8 version and newer ones. Also updated requirements.txt to `pyaudio>=0.2.11 `for future installs.
